### ISSUE TITLE
Error: Unable to load project after project creation

### ISSUE THREAD

**Issue by DeficientNull** [BanceDev/QuakePrism#2]
![image](https://github.com/BanceDev/QuakePrism/assets/17208311/eb2a891c-4bcb-431d-bc45-bd2e27f3c1cc)

I set everything up as i went along, directory is `fte/projects/test_qprism`.

I used the option to Import PAK, after it gives me this error it opens up the source folder but nothing else. Not sure if i'm doing something wrong or not.

**Comment by lancebord** [comment]
Do you have a quakeprism.cfg file in the same directory as the QuakePrism.exe?

**Comment by DeficientNull** [comment]
yes, it has the projects directory in it and nothing else.

**Comment by lancebord** [comment]
Ok then the app should be reading it correctly... Can you possibly post a video of you launching the app and creating this error. You should be able to just embed it in this thread.

**Comment by DeficientNull** [comment]
https://github.com/BanceDev/QuakePrism/assets/17208311/3d5c1d45-18f9-41ca-a82f-74bccc98181e

Here

**Comment by lancebord** [comment]
I was able to replicate your issue. This was not previously happening with the windows build so I need to look into the source code. Probably gonna have to roll out a hotfix for this. Thanks for the help

**Comment by DeficientNull** [comment]
No problem. Glad i could help!

**Comment by lancebord** [comment]
Fixed your issue, hotfix is available. Thanks again for the help. https://github.com/BanceDev/QuakePrism/releases/tag/v0.1.1-alpha
