### ISSUE TITLE
Error: "fteglqw64" not recognized as an internal or external command, program or batch file

### ISSUE THREAD

**Issue by DeficientNull** [BanceDev/QuakePrism#7]
![image](https://github.com/BanceDev/QuakePrism/assets/17208311/dfb0aa70-5d2b-42cd-800f-07e5aaf3f15b)

This is what happens when i try running with the fte executable from the UI. I already have set the sourceport "fteglqw64.exe" it just doesn't seem to recognize it.

**Comment by DeficientNull** [comment]
This also appears to happen with Quakespasm Spiked

**Comment by lancebord** [comment]
I think what's happening here is that the command is able to be translated using my Linux compatibility layer. I'm gonna test something really quickly that I think will fix this.

**Comment by DeficientNull** [comment]
![image](https://github.com/BanceDev/QuakePrism/assets/17208311/c1ea4d4f-53c0-4f38-9016-abcb21064d06)

Seems like a different version of the same error. I double checked to make sure the executable is in the same folder but alas.

**Comment by lancebord** [comment]
Adding this note for myself. I had a related report of an attempt to compile from windows using visual studio. I think the solution is to fixing these function calls. ![image](https://github.com/BanceDev/QuakePrism/assets/103229880/acf1baa0-0f06-4dbb-8bce-8ccee4a46302)

**Comment by lancebord** [comment]
@patrickmcurry wanna ping u on this as well.

Ok I've discovered that theres some issues with each of the functions called out above. Going to note needed changes here and then implement and test everything later today.

ShellExecute for file explorer:
```cpp
ShellExecuteA(NULL, "open", "C:\\", NULL, NULL, SW_SHOWDEFAULT);
```
ShellExecute for browser:
```cpp
ShellExecuteA(NULL, "open", "http://www.google.com", NULL, NULL, SW_SHOWDEFAULT);
```

chdir needs to be _chdir and use a windows formatted path

popen and pclose need to be _popen and _pclose and use a windows formatting as well

**Comment by DeficientNull** [comment]
![image](https://github.com/BanceDev/QuakePrism/assets/17208311/dd21b918-2535-40eb-ac79-487dbaccfc75)
picking fte and then clicking run in the latest patch gives me this error. Both PAK0 and PAK1 are already in both 01_projects and the actual folder just to be sure.

Compile went fine but compile and run crashes QuakePrism altogether.

**Comment by lancebord** [comment]
Is this new issue only an fte problem or also with vanilla engines. I've not seen this while using quakespasm

**Comment by DeficientNull** [comment]
with quakespasm spiked it just doesn't do anything when i click run. No erroe or anything on the console

**Comment by BanceDev** [comment]
Ok I'm going to assume there's something wrong with CreateSubprocess as its currently written. Going to try simplifying things using ShellExecute.

**Comment by lancebord** [comment]
fatal bugs related to this issue are taken care of, closing this issue. If further items pop up they will be under new issues.
